sunw-moon-9136/ssd-accept-all

test-shell/src/main/java/RunCommand.java
test-shell/src/test/java/RunCommandTest.java

```
testShell 에서 command 를 입력받아서 ssd.jar 를 실행시키는 부분을 개발하였습니다.
(우선은 read, write만)
```
💬 공유사항 to 리뷰어

TestShell read/write 입력 처리 부분

---

.gitignore
ssd/src/main/java/FileDriver.java
ssd/src/test/java/FileDriverTest.java

```
SSD 모듈의 File Read/Write를 처리하는 FileDriver 클래스의 write 기능을 구현하였습니다.
```
💬 공유사항 to 리뷰어

SSD FileDriver Write 기능

---

test-shell/settings.gradle.kts
test-shell/src/main/java/Output.java
test-shell/src/test/java/OutputTest.java

```
OUTPUT파일 있는지 확인하는 기능
OUTPUT파일내용 읽어오기
명령어 전달받는 것 까지 개발했습니다
```
- [ v] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [ v] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어

OUTPUT파일READ, 명령어 전달 받은 후 처리 기능 개발했씁니다

---

ssd/src/main/java/Controller.java
ssd/src/main/java/SsdController.java
ssd/src/test/java/SsdControllerTest.java

```
LBA와 주소 값 유효성 검사 추가
```
- [v] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [v] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어

[SSD] SsdController 인자 값 Validation 추가 완료

---

test-shell/src/main/java/DataReader.java
test-shell/src/main/java/Output.java
test-shell/src/main/java/OutputFileReader.java
test-shell/src/main/java/ReadOutputFactory.java
test-shell/src/main/java/RunCommand.java
test-shell/src/test/java/OutputTest.java
test-shell/src/test/java/RunCommandTest.java

```
UT시 factory 방식으로 mock 을 사용하기 위해  Refactoring
추가 파일
DataReader IF 
readOutputFactory  
실제 output파일을 factory로 처리하기 위한 class 
OutputfileReader
기존 ouput에서 파일 처리 부분을 별도 class로 분리
```
- [ v] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [ v] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어
Output 접근시 아래와 같이 사용하시면 됩니다.
Output output;
output = ReadOutputFactory.readOutput(); 
output.checkResult(command);

[Feat/output] output IF 도입으로 인한 output처리로직 refactoring

---

test-shell/src/main/java/Common.java
test-shell/src/main/java/Main.java
test-shell/src/main/java/RunCommand.java
test-shell/src/main/java/TestShell.java
test-shell/src/test/java/RunCommandTest.java
test-shell/src/test/java/TestShellTest.java

```
RunCommand.class, TestShell.class가 개발 완료됨에 따라 합치는 작업을 진행했습니다.
TestShell에서 RunCommand, Output 을 주입하여 호출하는 형식으로 개발을 진행했습니다.
```
💬 공유사항 to 리뷰어

RunCommand 내용 TestShell에 합치기

---

ssd/src/main/java/Ssd.java
ssd/src/main/java/SsdController.java
ssd/src/test/java/SsdControllerTest.java
ssd/src/test/java/SsdTest.java

```
read(), write() 메소드 구현
```
- [v] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [v] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어
flushOut의 경우, write 할때만 필요한 것 같아, read에서는 flush를 뺐습니다.

Feat/ssd Controller에 SSD 호출 부 추가

---

test-shell/src/main/java/DefaultTestScenario.java
test-shell/src/main/java/FullWriteAndReadCompare.java
test-shell/src/main/java/PartialLBAWrite.java
test-shell/src/main/java/RandomFactory.java
test-shell/src/main/java/WriteReadAging.java
test-shell/src/test/java/WriteReadAgingTest.java

```
Test Scenario 3 구현하였습니다.
```
💬 공유사항 to 리뷰어

Test Scenario 3 구현

---

test-shell/src/main/java/DefaultTestScenario.java
test-shell/src/main/java/Output.java
test-shell/src/main/java/TestShell.java
test-shell/src/test/java/FullWriteAndReadCompareTest.java
test-shell/src/test/java/OutputTest.java
test-shell/src/test/java/PartialLBAWriteTest.java
test-shell/src/test/java/TestShellTest.java
test-shell/src/test/java/WriteReadAgingTest.java

```
Test-Shell Address 출력 수정하였습니다.
```
💬 공유사항 to 리뷰어

Test-Shell Address 출력 수정

---

ssd/src/main/java/SsdController.java
ssd/src/test/java/SsdControllerTest.java

```
Erase 메소드에 validation 추가: size의 크기는 10이하다.
```
- [V] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [V] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [V] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어

ERASE 시 size의 크기는 10이하다

---

test-shell/src/main/java/shell/output/Output.java
test-shell/src/test/java/shell/output/OutputTest.java

```
output return 시 ssd_output.txt에서 읽은 값 그대로 return하도록 변경
write 시에만 "DONE" 리턴
```
- [v ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ v] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [ v] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어

Feat/runner) output return 값 포맷 변경

---

test-shell/src/main/java/driver/Driver.java
test-shell/src/main/java/driver/FileDriver.java
test-shell/src/main/java/logger/Logger.java
test-shell/src/test/java/logger/LoggerTest.java

```
Logger 1번 기능 구현하였습니다. 구현에만 초점을 맞춰 리팩토링이 좀 덜 되어 있을 수 있는 점... 주의 부탁드립니다.. 😂
추가로 ssd 모듈의 FileDriver를 그대로 복붙하여 사용 중입니다. 나중에 common 성 모듈로 옮길 필요가 있으나 우선 구현 자체를 빨리하기 위해 그렇게 진행한 점 참조 부탁드립니다...!
```

[feat]: Logger 1번 기능 구현

---

test-shell/src/main/java/Main.java
test-shell/src/main/java/shell/manager/IManager.java
test-shell/src/main/java/shell/manager/Manager.java
test-shell/src/main/java/utils/Valid.java
test-shell/src/test/java/MainTest.java
test-shell/src/test/java/shell/manager/ManagerTest.java

```
IManger, Manager를 분리하게 되면서 이전에 있었던 TestShell, Main 부분에 대해 refactoring을 진행하였습니다.
구조가 변경이 되면서 unit Test도 변경이 되어 새롭게 개발을 진행했습니다.
```
💬 공유사항 to 리뷰어

Main, Manager refactoring 및 unitTest

---

test-shell/src/main/java/driver/Driver.java
test-shell/src/main/java/driver/FileDriver.java
test-shell/src/main/java/logger/Logger.java
test-shell/src/test/java/driver/FileDriverTest.java
test-shell/src/test/java/logger/LoggerTest.java

```
Logger 2번 기능 내 Old Log File 이름 변경 구현하였습니다.
```

Logger 2번 기능 내 Old Log File 이름 변경 구현

---

test-shell/src/main/java/Main.java
test-shell/src/main/java/scenario/TestRunner.java
test-shell/src/test/java/scenario/TestRunnerTest.java
test-shell/src/test/java/shell/output/OutputTest.java

```
Test Script 목록이 들어있는 shell script를 가져와 test 하는 기능을 개발했습니다
```
- [x ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- [x ] Unit Test 100% Pass 여부
💬 공유사항 to 리뷰어
Main에서 runner를 실행하는 부분을 이렇게 하는게 맞을지 확인 부탁드립니다
if (args[0].length() > 0) {
TestRunner testRunner = new TestRunner(args[0]);
testRunner.process(processor, output);
return;
}

Runner 기능 구현하였습니다.

---

test-shell/src/main/java/driver/Driver.java
test-shell/src/main/java/driver/FileDriver.java
test-shell/src/main/java/logger/Logger.java
test-shell/src/test/java/driver/FileDriverTest.java
test-shell/src/test/java/logger/LoggerTest.java

```
Logger 2번 기능 중 Old Log File 확장자 변경 (log -> zip) 구현 완료하였습니다.
```

Logger 2번 기능 중 Old Log File 확장자 변경 (log -> zip) 구현

---

test-shell/src/main/java/shell/Processor.java
test-shell/src/test/java/shell/ProcessorTest.java

```
erase, erase_range, flush command 전달 추가, tc 추가했습니다.
```
💬 공유사항 to 리뷰어

erase, erage_range, flush command 전달

---

test-shell/src/main/java/Main.java
test-shell/src/main/java/shell/manager/IManager.java
test-shell/src/main/java/shell/manager/Manager.java
test-shell/src/main/java/utils/Common.java
test-shell/src/main/java/utils/Valid.java

```
shell 출력 및 main 함수 refactoring을 진행했습니다.
shell에 erase, flush 명령어 추가했습니다.
```
💬 공유사항 to 리뷰어

erase, flush 명령어 추가했습니다.

---

test-shell/src/main/java/driver/Driver.java
test-shell/src/main/java/driver/FileDriver.java
test-shell/src/main/java/logger/Logger.java
test-shell/src/test/java/driver/FileDriverTest.java
test-shell/src/test/java/logger/LoggerTest.java

```
Logger가 Append하지 않고 Truncate하고 있어서 Append하도록 수정
```

[fix]: Logger가 Append하지 않고 Truncate하고 있어서 Append하도록 수정

---

test-shell/latest.log
test-shell/src/main/java/scenario/TestRunner.java
test-shell/src/main/java/shell/output/Output.java
test-shell/src/main/java/shell/output/OutputFileReader.java
test-shell/src/test/java/shell/manager/ManagerTest.java
test-shell/src/test/java/shell/output/OutputTest.java

```
Output erase,erase_range, flush 추가
output checkResult 관련 refactoring
```
💬 공유사항 to 리뷰어

Output erase,erase_range, flush 추가 및 output refactoring

---

test-shell/src/main/java/Main.java
test-shell/src/main/java/shell/manager/Manager.java
test-shell/src/main/java/shell/output/Output.java
test-shell/src/test/java/scenario/TestRunnerTest.java
test-shell/src/test/java/shell/manager/ManagerTest.java

```
1. 로그 분석을 위해 각 함수에 대해 변수에 대해서도 log 추가했습니다.
2. unit Test 유지보수 진행했습니다.
```
💬 공유사항 to 리뷰어

Log 추가 및 unit Test 유지보수

---

test-shell/src/main/java/logger/Logger.java
test-shell/src/main/java/scenario/EraseAndWriteAging.java
test-shell/src/main/java/scenario/FullWriteAndReadCompare.java
test-shell/src/main/java/scenario/PartialLBAWrite.java
test-shell/src/main/java/scenario/TestRunner.java
test-shell/src/main/java/scenario/WriteReadAging.java
test-shell/src/main/java/utils/RandomFactory.java
test-shell/src/test/java/scenario/TestRunnerTest.java

```
Runner 기능 Fix 및 단위테스트 보강하였습니다 !
```

Runner 기능 Fix 및 단위테스트 보강

---

ssd/src/main/java/AbstractSsdOperator.java
ssd/src/main/java/DefaultSsdOperator.java
ssd/src/main/java/NandDriver.java
ssd/src/main/java/NandFileDriver.java
ssd/src/main/java/ReadWritable.java
ssd/src/main/java/SsdController.java
ssd/src/test/java/DefaultSsdOperatorControllerTest.java
ssd/src/test/java/DefaultSsdOperatorTest.java
ssd/src/test/java/NandFileDriverTest.java

```
각 컴포넌트의 확장성 및 추후 Builder 패턴 적용을 고려한 설계 변경건입니다.
ReadWritable 및 Nand 관련 변경 Test는 모두 통과하였고 Manager(기존 Controller)부분 수정시 Merge하여 확인예정입니다.
```
💬 공유사항 to 리뷰어

[refactor] 각 컴포넌트의 확장성 및 추후 Builder 패턴 적용을 고려한 설계 변경

---

test-shell/src/main/java/scenario/EraseAndWriteAging.java
test-shell/src/main/java/utils/Common.java

```
4_EraseAndWriteAging script 수정
helpText에 erase, erase_range, flush 추가
```
💬 공유사항 to 리뷰어

4_EraseAndWriteAging script 수정 및 helpText에 erase, erase_range, flush 추가

---

test-shell/src/test/java/shell/output/OutputTest.java

[test]: 미사용 테스트 케이스 삭제

---

test-shell/src/main/java/shell/manager/Manager.java
test-shell/src/main/java/shell/processor/Processor.java
test-shell/src/main/java/shell/processor/SSDRunner.java
test-shell/src/main/java/shell/processor/command/Command.java
test-shell/src/main/java/shell/processor/command/EraseCommand.java
test-shell/src/main/java/shell/processor/command/EraseRangeCommand.java
test-shell/src/main/java/shell/processor/command/FlushCommand.java
test-shell/src/main/java/shell/processor/command/ReadCommand.java
test-shell/src/main/java/shell/processor/command/WriteCommand.java
test-shell/src/test/java/shell/manager/ManagerTest.java
test-shell/src/test/java/shell/processor/ProcessorTest.java

```
기존 processor class 에 명령어 처리 로직이 모두 모여있어
command 패턴으로 개선해 보았습니다.
또한 변경된 구조에 맞춰 tc도 변경하였습니다.
```
💬 공유사항 to 리뷰어

Processor Refactoring

---

ssd/src/main/java/NAND/AbstractSsdOperator.java
ssd/src/main/java/NAND/DefaultSsdOperator.java
ssd/src/main/java/SsdManager.java
ssd/src/test/java/DefaultSsdOperatorTest.java

```
ReadWritable부 Builder로 구현
```
💬 공유사항 to 리뷰어

[refactor] ReadWritable부 builder화

---

ssd/src/main/java/SSD/InputFileHandler.java
ssd/src/test/java/InputFileHandlerTest.java

```
Buffer 최적화 관련하여 코드가 너무 복잡해 Refactoring 진행하였습니다.
```
💬 공유사항 to 리뷰어

[refactor] refactoring Input File Handler

---

ssd/src/main/java/SSD/InputFileHandler.java
ssd/src/test/java/InputFileHandlerTest.java

```
경계에 값이 존재하는 경우 발생하는 case 해결
```
💬 공유사항 to 리뷰어

[fix] 경계에 값이 존재하는 경우 발생하는 case 해결
